export enum Entity {
    Asteroid = 'Asteroid',
    Base = 'Base',
    BlackHole = 'BlackHole',
    City = 'City',
    Colony = 'Colony',
    Comet = 'Comet',
    Constellation = 'Constellation',
    Galaxy = 'Galaxy',
    Moon = 'Moon',
    Nation = 'Nation',
    Nebula = 'Nebula',
    Planet = 'Planet',
    Probe = 'Probe',
    Rover = 'Rover',
    Satellite = 'Satellite',
    Ship = 'Ship',
    Star = 'Star',
    Station = 'Station',
    Universe = 'Universe',
    Unknown = 'Unknown'
}